# Generated by Django 5.0.4 on 2024-08-17 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=250)),
                ('tgl_lahir', models.DateField()),
                ('name', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('hp', models.IntegerField()),
            ],
            options={
                'db_table': 'customer',
            },
        ),
    ]
