# Generated by Django 5.0.4 on 2024-08-17 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='hp',
            field=models.IntegerField(max_length=25),
        ),
    ]
