# Generated by Django 5.0.4 on 2024-08-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_customers_hp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='hp',
            field=models.FloatField(),
        ),
    ]
